import type { Product } from "@/lib/types";

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "sample-1",
    name: "Arduino Uno R3",
    description: "The standard lab board. USB-ready, plenty of I/O for first-year circuits and robotics kits.",
    base_price: 420,
    image_url: "/products/arduino.svg",
    is_available: true,
    created_at: new Date(0).toISOString(),
  },
  {
    id: "sample-2",
    name: "ESP32 DevKit",
    description: "Wi-Fi + Bluetooth microcontroller. Enough horsepower for IoT coursework without the Pi tax.",
    base_price: 280,
    image_url: "/products/esp32.svg",
    is_available: true,
    created_at: new Date(1).toISOString(),
  },
  {
    id: "sample-3",
    name: "Raspberry Pi 5 (8GB)",
    description: "Full Linux box for computer vision, servers, and graduation projects that outgrow a microcontroller.",
    base_price: 3850,
    image_url: "/products/pi.svg",
    is_available: true,
    created_at: new Date(2).toISOString(),
  },
  {
    id: "sample-4",
    name: "Solderless breadboard (830 tie)",
    description: "Full-size board with power rails. The thing you always wish you had two of.",
    base_price: 55,
    image_url: "/products/breadboard.svg",
    is_available: true,
    created_at: new Date(3).toISOString(),
  },
  {
    id: "sample-5",
    name: "Jumper wire pack (120 pcs)",
    description: "Male-male, male-female, female-female. Pre-cut, not the ones that oxidize after a week.",
    base_price: 45,
    image_url: "/products/jumpers.svg",
    is_available: true,
    created_at: new Date(4).toISOString(),
  },
  {
    id: "sample-6",
    name: "Digital multimeter",
    description: "Manual-ranging meter with continuity beep. Enough accuracy for lab reports, cheap enough to own.",
    base_price: 190,
    image_url: "/products/multimeter.svg",
    is_available: true,
    created_at: new Date(5).toISOString(),
  },
  {
    id: "sample-7",
    name: "Temperature-controlled soldering iron",
    description: "60W station with a stand and sponge. Temperature lock so lab partners stop cranking it to 450.",
    base_price: 520,
    image_url: "/products/iron.svg",
    is_available: true,
    created_at: new Date(6).toISOString(),
  },
  {
    id: "sample-8",
    name: "SG90 servo 4-pack",
    description: "Micro servos for arms, steering, and anything that needs 180 degrees of honest motion.",
    base_price: 160,
    image_url: "/products/servo.svg",
    is_available: true,
    created_at: new Date(7).toISOString(),
  },
  {
    id: "sample-9",
    name: "HC-SR04 ultrasonic pair",
    description: "Two distance sensors. One for the robot, one because the first one will get knocked off.",
    base_price: 70,
    image_url: "/products/ultrasonic.svg",
    is_available: true,
    created_at: new Date(8).toISOString(),
  },
  {
    id: "sample-10",
    name: "Resistor kit (1/4W, 1%)",
    description: "E12 series from 10Ω to 1MΩ, 20 of each. Sorted. Labeled. Not a bag of mystery stripes.",
    base_price: 85,
    image_url: "/products/resistors.svg",
    is_available: true,
    created_at: new Date(9).toISOString(),
  },
  {
    id: "sample-11",
    name: "16×2 LCD with I2C backpack",
    description: "Character display that does not eat half your GPIO. Contrast pot already on the backpack.",
    base_price: 95,
    image_url: "/products/lcd.svg",
    is_available: true,
    created_at: new Date(10).toISOString(),
  },
  {
    id: "sample-12",
    name: "PLA filament 1kg (1.75mm)",
    description: "Campus-color grey. Dry enough for overnight prints if you keep the bag sealed.",
    base_price: 610,
    image_url: "/products/filament.svg",
    is_available: true,
    created_at: new Date(11).toISOString(),
  },
];
